server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
#          uri: http://localhost:8888/
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter


        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/rating-service/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**




  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/